In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [4]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [5]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [7]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
reshaped_array = range_array.reshape(4,2)
reshaped_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
random_array = np.random.random((4,5))
random_array

array([[0.72673003, 0.48656602, 0.49075013, 0.6731329 , 0.75441547],
       [0.5392553 , 0.2425138 , 0.22851367, 0.93934215, 0.83983475],
       [0.15395053, 0.92253033, 0.03125596, 0.24980447, 0.8476736 ],
       [0.47176369, 0.89075912, 0.56739518, 0.87985603, 0.7607645 ]])

In [12]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
mean = np.mean(range_array)
mean

3.5

In [14]:
median = np.median(range_array)
median

3.5

In [15]:
var = np.var(range_array)
var

5.25

In [16]:
std = np.std(range_array)
std

2.29128784747792